@server = https://fluffy-space-telegram-wr944pqjq64hgg6w-8080.app.github.dev
####
GET {{server}}/api/instrumentos
####
POST {{server}}/api/intrumentos
Content-Type: application/json

{"firstName": "David", "lastName": "Nicola", "description": "Davicho"}

