@server = https://fuzzy-waffle-ggv9q5rvpxw3w9g-8080.app.github.dev
####
GET {{server}}/api/instrumentos
####
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Flauta", "categoria": "Viento", "descripcion": "Plastico"}
#####
GET {{server}}/api/musicos
####
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Sin Bandera"}

